src/core/javascripts/controllers/client_details.js.coffee, src/core/javascripts/controllers/login.js.coffee, src/core/javascripts/services/login.js.coffee
Angular changes for this ticket
https://bookingbug.atlassian.net/browse/BOOK-559
=> Jack angular login

src/core/javascripts/controllers/day_list.js.coffee, src/core/javascripts/controllers/duration_list.js.coffee, src/core/javascripts/controllers/time_list.js.coffee
For duration, day and time lists. Alert services have also been added.
=> Attn: Luke; Subject: bb-page checker v01

src/core/javascripts/controllers/service_list.js.coffee, src/public-booking/templates/_price_filter.html, src/public-booking/templates/service_list.html
Hi Luke,
The service list filter can be test in the examples folder (once a suitable development config file gets created; I couldn't seem to commit it for some reason). And it can be test with mjm's folder in bespoke.
=> Attn: Luke; Subject: Service list filter updates

src/core/javascripts/controllers/time_range_list.js.coffee, src/core/javascripts/services/time.js.coffee, src/core/javascripts/services/widget.js.coffee
Passing specific multiple resources to API
=> [COV-2]handling multiple resources

package.json
There were duplicated objects inside package.json file 2x devDependencies, scripte, author, and license . Plus duplicated dependencies so I delete them and clean up the package.json
Pls. check before merging :8ball: .
THX !!
=> Gracjan package fix

src/core/javascripts/services/time.js.coffee
Assignment of bookings to be random
=> [LIFE-8] Angular journey select random staff (person).

src/core/javascripts/controllers/item_details.js.coffee, src/core/javascripts/controllers/total.js.coffee, src/core/javascripts/purchase/controllers/purchase.js.coffee, src/core/javascripts/purchase/models/booking.js.coffee, src/core/javascripts/purchase/services/purchase.js.coffee, src/core/javascripts/services/error.js.coffee, src/public-booking/stylesheets/_buttons.scss, src/public-booking/templates/_cancel_modal.html, src/public-booking/templates/event.html
- Updated bbTotal to only use PurchaseService when bb.total is not set
- BREAKING CHANGE: updated few methods in bbPurchase/PurchaseService to use camelCase
- Updated BookingPurchase model to set first/last name on post data
=> Change attendee updates [SKYG-24], including:

src/core/javascripts/controllers/base.js.coffee, src/core/javascripts/directives/fb_login.js.coffee, src/core/javascripts/directives/member_login.js.coffee
This pull request is to add a new total app based redirectTo method. Then removed it from the directive that had this method defined as it was not unneeded.
=> [DEBS-183] Added default redirectTo method for the widget.

src/core/javascripts/controllers/client_details.js.coffee, src/core/javascripts/services/error.js.coffee, src/core/javascripts/services/validator.js.coffee
Invalid error handling and error message. Also new regex for front end password validation.
=> invalid email error handling and regex

src/core/javascripts/controllers/item_details.js.coffee
Fix scope of slot_id when moving a booking, now is updated with the one returned from the backend
=> SKYG-42 hotfix

src/core/javascripts/controllers/service_list.js.coffee, src/public-booking/templates/client_admin.html
requires https://github.com/Glenn/bookingbug/pull/941 merged and deployed
=> [DUN-3] client  address if ask_address

src/admin/javascripts/main.js.coffee, src/core/javascripts/controllers/event.js.coffee, src/core/javascripts/controllers/event_list.js.coffee, src/core/javascripts/models/base.js.coffee, src/core/javascripts/models/event.js.coffee, src/core/javascripts/purchase/controllers/purchase.js.coffee, src/core/javascripts/purchase/models/booking.js.coffee, src/core/javascripts/purchase/models/total.js.coffee, src/core/javascripts/services/loading.js.coffee, src/core/javascripts/services/login.js.coffee, src/member/javascripts/controllers/member_bookings.js.coffee, src/member/javascripts/directives/member_bookings_table.js.coffee, src/member/javascripts/main.js.coffee, src/member/javascripts/services/login.js.coffee, src/services/javascripts/models/person.js.coffee, src/services/javascripts/services/person.js.coffee
=> Version2 fixes

src/core/javascripts/controllers/time_range_list.js.coffee
Before we were just checking if the time slot was different.. and not checking at all if the person changed
=> [CB-143] Move booking even when is just the staff changing

src/core/javascripts/models/basket_item.js.coffee
Obscure bug fix in 2 parts. SDK and API. Might need revisiting at some point.
=> [MOTH-22][PART1-API] attach answers to item_details.questions

src/core/javascripts/controllers/base.js.coffee, src/core/javascripts/directives/helpers.js.coffee
Updated bbApiUrl directive to bind to the iframe load event to detect when it has loaded, instead of use timeout/window method.
=> [KBC-39] IE8 fix

src/core/javascripts/controllers/item_details.js.coffee
Please note Atom has removed some white space throughout the file, the actual changes are from lines 224 - 239 inside the confirm_move method.
=> [SKG-85] Variable for a custom booking icon when moving a booking.

src/core/javascripts/directives/main.js.coffee, src/core/javascripts/models/time_slot.js.coffee
Creating a moment object that we can format accordingly on time slots. Additionally its a model directive expansion in main that Luke has already looked over.
=> [CAPONE-42] This pull request is for capone 42.

src/core/javascripts/purchase/controllers/purchase.js.coffee
Translation for generic alerts.
=> [CAPONE-40] Translation enable for generic alerts.

src/core/javascripts/controllers/base.js.coffee, src/core/javascripts/controllers/checkout.js.coffee, src/core/javascripts/controllers/total.js.coffee
Reverts BookingBug/bookingbug-angular#163
=> Revert "[CAPONE] back button fix"

src/admin-booking/javascripts/directives/block-time.js.coffee, src/admin-booking/templates/quick_pick.html
For the week and month view that dont have a pre selected resource
=> PLAT-62 adding a resource picker to the block section

src/admin-dashboard/javascripts/main.js.coffee
Small fix to avoid console errors regarding company_id value missing
=> Fixing issue with errors where the service is not actually required

src/admin-dashboard/javascripts/directives/resource_calendar.js.coffee
Tapped into the fullcalendar date to update the date picker, also removed the initialization of the current date as this is overwritten anyway. My text editor has removed a lot of white space so please refer to lines 190 and 343.
=> Oriental 78

src/core/javascripts/controllers/accordian_range_group.js.coffee, src/core/javascripts/controllers/time_range_list.js.coffee, src/public-booking/stylesheets/_calendar.scss
Added a method to disable slots by passing in iso date and time.
=> [CAPONE-165] Added a method to disable slots

src/core/javascripts/controllers/item_details.js.coffee, src/core/javascripts/main.js.coffee, src/core/javascripts/models/basket_item.js.coffee, src/core/javascripts/services/i18n/en-gb.js, src/core/javascripts/services/settings.js.coffee
At the moment, the moved booking date is only displaying in UK format. An extra condition has been created to display it in US format.
=> [AVE-18] Show booking moved date with US date format condition

src/core/javascripts/services/unwrap.js.coffee
This change is to make it so that less code is repeated im not sure how the best way to test this is with v2 is but it functions perfectly before the swap. Additionally the file is the same between v1 and v2 so it should work.
=> Pr unwrap dry

src/core/javascripts/i18n/controller/language_picker.controller.js.coffee, src/core/javascripts/i18n/services/locale.service.js.coffee
as requested by Damian. Can't review own PRs.
=> locale improvements

src/admin-dashboard/stylesheets/_form.scss, src/admin-dashboard/stylesheets/main.scss, src/public-booking/stylesheets/_form.scss
Changed the error message icon from glyphicons to it's font-awesome equivalent.
<h3 align="center">
Before:  implementing changes :
</h3>
**Screenshot:**
<h3 align="center">
After:  implementing changes :
</h3>
**Screenshot:**
=> change error message icon from glyphicons to fontawesome equivalent.

src/core/javascripts/controllers/time_range_list.js.coffee, src/core/templates/accordion-group.html, src/public-booking/stylesheets/_calendar.scss, src/public-booking/templates/_accordion_range_group.html, src/public-booking/templates/calendar.html
added ability to tab through calendar accordion, skips unavailable slots and focus on continue button after selecting a slot
=> calendar accessibility 

src/core/javascripts/controllers/event_list.js.coffee, src/public-booking/templates/event_list.html
Made same changes as on version 1  at -> https://github.com/BookingBug/bookingbug-angular/pull/536
=> [IMPL 1399] changes for version 2 (master branch)

src/core/javascripts/controllers/event_list.js.coffee, src/public-booking/templates/event_list.html
- Renamed '$scope.filters.hide_sold_out_events' to '$scope.filters.hide_fully_booked_events' in the javascript file and made corresponding changes in public-booking/templates file.
- $scope.filters.hide_fully_booked_events initially set to 'false'.
=> [IMPL-1399] renamed '$scope.filters.hide_sold_out_events' to '$scope.filters.hide_fully_booked_events'

src/core/javascripts/controllers/event_list.js.coffee
forgot to add comma before the function parameter. Also changed _.forEach to _.each to be more consistent.
=> Fix dynamic filters 2

src/core/javascripts/controllers/person_list.js.coffee, src/core/javascripts/controllers/resource_list.js.coffee
Fix skipping person_list/resouce_list when they have been set in item_defaults.
<h3 align="center">
After:  implementing changes :
</h3>
**With passing in person id:**
**Without passing in person id:**
=> [IMPL-1328] fix skip to next step on person_list and resouce_list

src/core/javascripts/controllers/person_list.js.coffee
@lukeferguson @damianpudlo 
The same fix that I made for SDK Version1, which is now included in release v1.4.98.
=> Fix the auto selection of person when merge_people is set to true

src/admin-dashboard/javascripts/login/directives/admin_dashboard_login.js.coffee, src/admin-dashboard/templates/login/admin-dashboard-login.html, src/admin/javascripts/controllers/login.js.coffee, src/admin/templates/login/admin_login.html, src/admin/templates/login/admin_pick_company.html
**Change Notes :**
- Renamed 'login_form' to 'login_data' to avoid sharing scope with 'login_form' created by 'ng-form'.
- Please see change request in comment at https://github.com/BookingBug/bookingbug-angular/pull/532 .
=> renamed 'login_form' to 'login_data'.

src/admin-booking/templates/calendar.html, src/core/javascripts/directives/main.js.coffee, src/public-booking/templates/calendar.html
- Same changes for version2(`master` branch) as done for `version1` at https://github.com/BookingBug/bookingbug-angular/pull/579
=> Scroll to selected timeslot v2

src/public-booking/templates/purchase.html
- Made same changes for `version1` branch as done for `master` branch at https://github.com/BookingBug/bookingbug-angular/pull/588 and https://github.com/BookingBug/bookingbug-angular/pull/590
=> Fix purchase ui (same changes as #588 and #590, but for 'version1' branch)

src/public-booking/templates/purchase.html
**Change Note:** 
Fix space between `ng-show` and `class`.
=> Fix space between `ng-show` and `class`

src/core/javascripts/directives/steps_directives/bb_total/bb_total.controller.js.coffee
- Made same change of adding in missing `PurchaseService` as has been done in `version1` branch at https://github.com/BookingBug/bookingbug-angular/blob/version1/src/core/javascripts/controllers/total.js.coffee#L43.
=> added in missing PurchaseService.

src/core/javascripts/controllers/map.js.coffee
**Note:**
- Same changes as made for `master` branch at https://github.com/BookingBug/bookingbug-angular/pull/615
- fixed centring on current marker on the google map.
- fixed google maps to respect default zoom if it is passed into the directive
=> (version1) fix google maps to centre on open marker and respect default zoom if passed in

src/core/javascripts/models/base.js.coffee, src/core/javascripts/models/booking_text.js.coffee, src/core/javascripts/services/unwrap.js.coffee
- Adds `BookingText` model and unwrapping service
- Fixed GetSomeModel BaseModel methods where `BB.Service.some_model` module doesn't exist
=> [IMPL-248] BookingText model and unwrapping service

src/core/javascripts/directives/inputs/bb_form.directive.js
- provide config options on bbForm
- `no-route`(do not call `decideNextPage()`).
- `disable-auto-submit`(do not trigger auto form submission).
=> Provide config options on bbForm: 'no-route', 'disable-auto-submit'

src/core/javascripts/directives/inputs/bb_form.directive.js
=> clean up in #688

src/admin-dashboard/stylesheets/_default-theme.scss
- admin-dashboard - set brand logo path as a variable so that it can be easily overridden.
=> admin-dashboard - set brand logo path as a variable so that it can be easily overridden.

src/admin-booking/javascripts/translations/en.js
Change Note:
- [IMPL-2313] fix translation key value.
=> [IMPL-2313] fix translation key value.

src/admin-booking/templates/admin-booking/admin_resources_dropdown.html, src/core/javascripts/filters/main.js
Change Note:
- [IMPL-2325] fix translation keys.
=> [IMPL-2325] fix translation keys.

src/queue/templates/queue/selected_queuer.html
- [IMPL-2325] fix text display of estimated wait time when overdue.
=> [IMPL-2325] fix text display of estimated wait time when overdue.

src/queue/javascripts/controllers/queue_server.js
- [IMPL-2317] add back the functionality to 'Mark Absent'.
=> [IMPL-2317] add back the functionality to 'Mark Absent'.

src/queue/templates/queue/server.html
- [CORE-1747] fix click on green queuer box in server view.
_(Note how clicking on a queuer does nothing)_
_(Note how clicking on a queuer now opens up the info card)_
=> [CORE-1747] fix click on green queuer box in server view.

src/queue/javascripts/controllers/queue_server.js
- [IMPL-2330] fix removing disable from buttons on completing the server request.
=> [IMPL-2330] fix removing disable from buttons on completing the server request.

src/queue/templates/queue/queue_server_actions.html
- [IMPL-2389] disable 'Serve Next' button if no waiting queuers.
=> [IMPL-2389] disable 'Serve Next' button if no waiting queuers.
