src/core/javascripts/controllers/basket.js.coffee, src/core/javascripts/services/error.js.coffee
Added $attrs dependancy to controller BasketList so that requires_deal can be assigned to bb.basket.settings using bb-basket-list='{requires_deal:true}'.
Updated setReady() so it now fails if settings.requires_deal is true and hasDeal() returns false (do not proceed to checkout).
Added a new error object to errors.js.coffee - "GIFT_CERTIFICATE_REQUIRED"
Resolved merge conflict by removing ErrorService dependancy and adding $attrs dependancy from/to BasketList controller and using the new AlertService.raise(<error_key>) method for "GIFT_CERTIFICATE_NOT_FOUND"
=> Scope.bb.basket.settings.requires deal

src/core/javascripts/controllers/base.js.coffee
Add availability-slots to avoid checking slots when its not needed
with reference to this: https://github.com/Glenn/bookingbug/pull/786
=> HOTFIX - default angular admin journey broken

src/core/javascripts/controllers/base.js.coffee, src/core/javascripts/controllers/item_details.js.coffee, src/core/javascripts/controllers/resource_list.js.coffee, src/core/javascripts/controllers/service_list.js.coffee, src/core/javascripts/services/widget.js.coffee
- Updated loadPreviousStep() to take account of skipped steps so it loads the correct step when going back
- Updated skipThisStep() to mark the current step as skipped - manipulating current_step had no affect as recordCurrentPage() in the widget service always overrode it as a new page is loaded
- Updated bbResources directive with allow_single_pick option akin to bbServices
- Refactored bbServices to mark step as skipped before it routes to the next page
=> Updated SDK to record skipped steps:

src/core/javascripts/models/basket_item.js.coffee
The bit `@base_price = @service.getPriceByDuration(dur)` was working correctly and setting the price as expected when the booking duration changed (i.e. when the duration doubles, the price doubles)
But the following lines would then undo that work and change the price back to the original price, before multiplication.
I've added some `else if`s to sort that out.
=> amended setDuration to honour duration price changes

src/core/javascripts/controllers/base.js.coffee
Now that we clear the steps on checkout it can throw a air-break error if we dont have that step. This should fix that.
=> [CAPONE-137] title set check step exists

src/core/javascripts/controllers/base.js.coffee
So the current step is not representative of the step then we set it to all steps so it gets the correct title.
=> [CAPONE] airbrake title fix 2.0

src/admin-dashboard/javascripts/directives/resource_calendar.js.coffee
add $scope.blockLabelAssembler to bbResourceCalendar directive to mark blocked events with the description "Blocked" for easier visual distinction of blocked events and ultimately improved user experience.
=> [ORIENTAL-69] extend #labelAssembly for blocked events

src/public-booking/stylesheets/bb-sass-3-3-1/_print.scss
max width important class breaks gmap integration and added the rel css to hide the long ref url when printing.
=> [JACK] The map will not show so i fixed it.

src/core/javascripts/controllers/base.js.coffee
This change is so that you use the last item in the basket as the current_item if there is not a current already set by the ref. This will prevent some odd restoring especially when the back button is triggered.
=> PR-ref-changes

src/core/javascripts/models/client.js.coffee
Strip off the leading zero in `fullMobile`.
=============
**Change Notes:** Modified ClientModel to strip off the leading zero in `fullMobile`.
<h3 align="center">
Before:  implementing changes :
</h3>
<h5>
Screencast :
</h5>
**Note:** notice how the zero is being added after the prefix(+44) in the 'Mobile' field under 'Bennnny'.
<h5>
Screenshot :
</h5>
**Note:** notice how the zero is being added after the prefix(+44) in the 'Mobile' field under 'Bennnny'.
<h3 align="center">
After:  implementing changes :
</h3>
**Note:** notice how the zero is now not added after the prefix(+44) in the 'Mobile' field under 'Bennnny'.
=> ClientModel - strip off the leading zero in fullMobile.

src/admin-dashboard/javascripts/login/directives/admin_dashboard_login.js.coffee, src/admin-dashboard/templates/login/admin-dashboard-login.html, src/admin/javascripts/controllers/login.js.coffee, src/admin/templates/login/admin_login.html, src/admin/templates/login/admin_pick_company.html
Renamed variable name which was also defined with the same name as a function later within the same file.
'$scope.login' had been defined as a variable and also as a function later within the same file.
Hence, the function definition was essentially overriding the previously defined variable.
Note that this was observed on both 'admin' and 'admin-dashboard'.
=> scope.login defined twice within same file

src/public-booking/stylesheets/_calendar.scss
Fixed greying-out unavailable slots on the calendar page.
_(Note how the unavailable time slots are not greyed-out)_
_(Note how the unavailable time slots are now greyed-out)_
=> fixed greying-out unavailable time slots on calendar page.

src/core/javascripts/controllers/person_list.js.coffee, src/core/javascripts/controllers/resource_list.js.coffee
Made same changes as done for PR on version 1(https://github.com/BookingBug/bookingbug-angular/pull/541), to fix skipping person_list/resouce_list when they have been set in item_defaults.
<h3 align="center">
After:  implementing changes :
</h3>
**With passing in person id:**
**Without passing in person id:**
=> [IMPL-1328] fix skip to next step on person_list and resource_list(same as for version 1)

src/core/javascripts/controllers/time_range_list.js.coffee
Fixed setting 'skipped' on the 'calendar' page when it auto-skips to the next page, so that clicking 'Back' button on the next page(generally 'check_items' pages/'review page') behaves as expected, that is, it routes back to the 'service_list' page.
<h3 align="center">Before:  implementing changes : </h3>
<h3 align="center">After:  implementing changes : </h3>
=> Fixed setting 'skipped' on the 'calendar' page when it auto-skips to the next page

src/core/javascripts/controllers/time_range_list.js.coffee
Fixed setting 'skipped' on the 'calendar' page when it auto-skips to the next page, so that clicking 'Back' button on the next page(generally 'check_items' pages/'review page') behaves as expected, that is, it routes back to the 'service_list' page.
<h3 align="center">Before:  implementing changes : </h3>
<h3 align="center">After:  implementing changes : </h3>
=> [Version 1] Fixed setting 'skipped' on the 'calendar' page when it auto-skips to the next page

src/core/javascripts/services/day.js.coffee, src/core/javascripts/services/time.js.coffee
* TimeService and DaySerivce now accept `people_ids` and `resourc_ ids `
* Coffied operators and tidied up code
* Removed `location`, `person_id`, and `resource_id` params from `DayService` - these are not supported by the day data API!
=> [CORE-1075] [CORE-1086] Updated day/time service to accept multiple people

src/admin-booking/javascripts/directives/admin_booking.js.coffee
**Notes :** 
Ensure that the 'bbAdminBooking' directive creates a new child scope that prototypically inherits from the parent scope to avoid it over-writing the rootScope.
While creating a directive, 
default (scope: false) - the directive does not create a new scope.
Hence we need to set it to true.
Please see AngularJS Documentation at : https://github.com/angular/angular.js/wiki/Understanding-Scopes#directives for more information.
=> Fix bbAdminBooking' over-writing rootScope.

src/admin-booking/javascripts/directives/admin_booking.js.coffee
**Notes :** 
Ensure that the 'bbAdminBooking' directive creates a new child scope that prototypically inherits from the parent scope to avoid it over-writing the rootScope.
While creating a directive, 
default (scope: false) - the directive does not create a new scope.
Hence we need to set it to true.
Please see AngularJS Documentation at : https://github.com/angular/angular.js/wiki/Understanding-Scopes#directives for more information.
=> Fix bbAdminBooking' over-writing rootScope (v2)

src/public-booking/javascripts/translations/en.js.coffee
- Fixed accordion on calendar page to be consistently aligned by modifying translation value.
_(Note how the accordion is inconsistently aligned when there is only 1 available time slot)_
_(Note how the accordion is now consistently aligned)_
=> Fix accordion on calendar page to be consistently aligned.

src/core/javascripts/controllers/time_range_list.js.coffee
- Added a delay and scroll animation between after selecting a time slot and focussing on continue button.
_(Note how the accordion seems to move up and down rapidly on selecting a time slot)_
_(Note how the transitions now seem smoother on selecting a time slot)_
=> Smoothen transition between selecting a time slot and focussing on continue button.

src/public-booking/stylesheets/_buttons.scss, src/public-booking/stylesheets/_calendar.scss, src/public-booking/stylesheets/_page.scss
- Changed colour of border on focused elements to be consistent with border on focused input elements.
_(Note the border colour on the focused element is browser specific, the one displayed below is on Google Chrome)_
_(Note that the border colour on the focused element is not browser specific and is consistent with the border on a focused input element)_
=> change colour of border on focused elements to be non browser specific and consistent with input elements

src/public-booking/templates/purchase.html
- Fixed `Book Waitlist Items` button to be in line with cancel/move booking button.
_(Note how the `Book Waitlist Items` button is mis-aligned)_
_(Note how the `Book Waitlist Items` button is now properly aligned)_
=> fix book waitlist button to be in line with cancel/move booking button.

src/public-booking/templates/purchase.html
- Fixed not showing booking details when booking has already been cancelled.
_(Note how the booking details are being incorrectly shown when booking has already been cancelled)_
_(Note how the booking details are now being hidden when booking has already been cancelled)_
=> fix not showing booking details when booking has already been cancelled.

src/core/javascripts/controllers/event_list.js.coffee
Now that the API includes `member_level_id` in client model soar, we should query event chains specifying `member_level_id` URL param so we can display the discounted price before checkout.
=> [IMPL-722] Member level pricing

src/admin-dashboard/javascripts/calendar/controllers/resource_calendar.controller.js.coffee
- fixed error "Cannot read property 'target' of undefined" to support calling 'select_method' of FullCalendar programmatically.
Please see FullCalendar Documentation at https://fullcalendar.io/docs/selection/select_callback/.
The documentation points out that "If select has been triggered via the select method, jsEvent will be undefined".
=> [CORE-168] fixed error 'Cannot read property target of 'undefined'".

src/admin-dashboard/javascripts/calendar/directives/bbResourceCalendar.js.coffee
- Same changes as made for 'master' branch at https://github.com/BookingBug/bookingbug-angular/pull/613 .
**Details:**
- fixed error "Cannot read property 'target' of undefined" to support calling 'select_method' of FullCalendar programmatically.
Please see FullCalendar Documentation at https://fullcalendar.io/docs/selection/select_callback/.
The documentation points out that "If select has been triggered via the select method, jsEvent will be 'undefined'".
=> [CORE-168] (version1) fixed error 'Cannot read property target of 'undefined'".

src/core/javascripts/directives/steps_directives/bb_map/bb_map.controller.js.coffee
- fixed centring on current marker on the google map.
- fixed google maps to respect default zoom if it is passed into the directive
_(Note how the map is not centred  on the open marker and the default zoom is not being respected)_
_(Note how the map is now centred on the open marker and the default zoom which was set to 6 is respected)_
=> fix google maps to centre on open marker and respect default zoom if passed in

src/core/javascripts/directives/bb_widget/bb_widget_init.service.js, src/core/javascripts/directives/steps/bb_map/bb_map.controller.js, src/core/javascripts/services/general_options.js
- ability to re-initialise the map page during runtime without reloading the page.
- moved the functionality to initialise the map page into `$scope.initialise`
- ability to choose to stay on the same page when calling selectItem() on the map page.
- `no_route` option which when set to true, selectItem() does not call decideNextPage() when calling $scope.initWidget().
```bb-map="{no_route: true}"```
- ability to set a custom map marker icon via GeneralOptionsProvider
```
GeneralOptionsProvider.setOption('map_marker_icon', 'images/example_image_name.png');
```
-  ability to only fill in the address and not load the map when calling geolocate()
```
ng-click="geolocate(false)"
```
- corrected `return` statements and calls to `loader.notLoaded()`, `loader.setLoaded()`.
=> [IMPL-2002] improvements for bb-map

src/core/javascripts/directives/steps/bb_map/bb_map.controller.js
- [IMPL-2002] only call 'setMarkers' in 'showClosestMarkers', if 'shownMarkers' exist on scope.
=> [IMPL-2002] only call 'setMarkers' in 'showClosestMarkers', if 'shownMarkers' exist on scope.

src/core/javascripts/services/scrollIntercepter.js
- [IMPL-2004] fix 'bb-scroll-to' to scroll correctly on a modal.
**Details:**
It was noticed that if `bb-scroll-to` was set on an element located on a page loaded inside a modal, rather than scrolling to the appropriate element, the page was scrolling in the greyed background of the modal. This was due to the code calling the scrollTop function on the wrong context(the html, body) instead of on the modal(when the modal is open).
=> [IMPL-2004] fix 'bb-scroll-to' to scroll correctly on a modal.

src/admin-dashboard/javascripts/core/services/side_navigation_partials.js
- [IMPL-2318] removed adding orphanItems to the ordered list (side_navigation).
**Details:**
It was noticed that the setting the `side_navigation` option in `AdminCoreOptionsProvider` as follows,
```
AdminCoreOptionsProvider.setOption('side_navigation', [
{
group_name: 'SIDE_NAV_QUEUING',
items: ['queue']
}, {
group_name: 'SIDE_NAV_BOOKINGS',
items: ['calendar', 'clients']
}, {
group_name: 'SIDE_NAV_CONFIG',
items: ['config-iframe', 'publish-iframe', 'settings-iframe']
}
]);
```
was not being respected since `orphanItems` were being added to the end of the array `$scope.navigation`.
=> [IMPL-2318] removed adding orphanItems to the ordered list (side_navigation).

src/queue/javascripts/controllers/queue_server.js, src/queue/templates/queue/queue_server_actions.html
- [IMPL-2317] show modal popup on clicking 'Finish Serving' only if schemaForm returns with 'Outcomes' tab.
**Details:**
- `Problem` : On the new Queuing Interface on Admin Studio, under the Concierge view, it was noticed that in the CYBG project, they did not have any outcomes configured on the back-end for the schema form to return with on clicking 'Finish Serving'. This would show an unnecessary modal popup irrespective of whether there are any outcomes or none.
- `Proposed solution` :
- Ideally we should check if there are any outcomes and only show the modal popup in that case.
- The schema form from booking.$get('edit') has this information in it.
- This fix makes  the modal resolve schema promise-reject if there aren't any outcomes and then have the …
=> [IMPL-2317] show modal popup on clicking 'Finish Serving' only if schemaForm returns with 'Outcomes' tab.

src/admin-dashboard/javascripts/core/directives/bb_admin_dashboard.js, src/admin-dashboard/templates/core/layout.html
- fix copyright year to always be the current year.
_(Note the copyright year is `2016`)_
_(Note the copyright year is now correctly `2017`)_
=> fix copyright year to always be the current year.

src/queue/templates/queue/selected_queuer.html
- [IMPL-2325] changed '<' to use HTML character entity reference '&lt;'.
=> [IMPL-2325] changed '<' to use HTML character entity reference '&lt;'.
